// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjkyqueaouftmrfspoiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qa3lxdWVhb3VmdG1yZnNwb2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjI4MjAsImV4cCI6MjA1ODM5ODgyMH0.N7Kls0x9Dahl2Y1dU_-lxIwov61itn_fTxTXgoVUWic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);